### ISSUE TITLE
Shape is not a constructor

### ISSUE THREAD

**Issue by zhaodianlong** [moefyit/moefy-vuepress#1]
![image](https://user-images.githubusercontent.com/22448698/83738947-87f50900-a687-11ea-87b6-586c6bf1ec08.png)

**Comment by SigureMo** [comment]
能否详细描述下问题？貌似是插件 `cursor-effects` 出现问题了，检查下 `config.js` 该插件的配置是否有问题？配置方法可以参考

https://github.com/moefyit/moefy-vuepress/blob/master/docs/.vuepress/config.js#L16-L23

如果没有解决，贴一下你的 `config.js`

**Comment by SigureMo** [comment]
长时间没有回应，暂时关闭，如果有问题可以 reopen
